### ISSUE TITLE
reported an error

### ISSUE THREAD

**Issue by zxg519** [kamakshidasan/irrelevant#1]
I tried to run this tool, and put one tetrahedra mesh file in input directory. After running "python run.py" paraview is launched but report the following error:

---------------------------------------------------------------------------------------------------
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
  File "<string>", line 269
    spreadSheetView1.BlockSize = 1024L
                                     ^
SyntaxError: invalid syntax
context mismatch in svga_sampler_view_destroy
beijing_small_speed1_longlat_heading_L0_116_xy_fre_sigma_1.4_mode_4_kde3D_xyscale_0.3.vtk Done :) 126  files remaining
adhitya.vtk aishwarya
Traceback (most recent call last):
  File "run.py", line 34, in <module>
    replace_wildcard(compute_file, file_list[i-1], file_list[i])
IndexError: list index out of range

**Comment by kamakshidasan** [comment]
Hi -- sorry for the late reply.

To the best of my knowledge, there should be three steps.

1. rename your file to tv_0.vtk
2. edit this line https://github.com/kamakshidasan/irrelevant/blob/master/scripts/run.py#L29 to 1
3. make sure you created all folders from Lines 60-94 over here: https://github.com/kamakshidasan/irrelevant/blob/master/scripts/helper.py#L60

Just a question: what version of TTK are you using? Why is this repository interesting to you?

Feel free to add more issues, if you find any.
